### ISSUE TITLE
文章列表下，標籤不見了

### ISSUE THREAD

**Issue by kun-yu-tsai** [nexfoundation/vanilla#105]
需要研究一下，把他加回來

<img width="947" alt="Screenshot 2021-03-28 at 17 19 49" src="https://user-images.githubusercontent.com/9505724/112747735-d0502f80-8fe9-11eb-818c-71d4ee4fc1ec.png">

**Comment by blueworrybear** [comment]
@kun-yu-tsai 
I think I could assist with this issue, would you mind assign this one to me?

**Comment by kun-yu-tsai** [comment]
@blueworrybear , no problem mate. Thanks~!

**Comment by blueworrybear** [comment]
@kun-yu-tsai @tcssh611503 

It seems to me that this is a bug because the original code tries to search discussion item with it's ID.
However, the ID used by the code is as the same as the index number of the discussion across all discussion nodes,
which is not true.

I have updated the code to fix this issue. If you found any problem of my update, please let me know.

**Comment by kun-yu-tsai** [comment]
Hi, @blueworrybear. I have read the code and agree with your comments. I think it was originally getting the elements with the wrong func and params. Thanks a lot, bro~
