### ISSUE TITLE
未開放使用者自定義標籤，則應移除「開始錄製」的提示選項

### ISSUE THREAD

**Issue by AB-Y** [nexfoundation/vanilla#169]

**Comment by AB-Y** [comment]
如題，目前未開放使用者可以自行輸入 tag
但在發文時， tag 欄位還是在輸入任意文字後跳出「開始錄製」字樣 >>> 正確作法應移除該提示
<img width="825" alt="截圖 2021-04-15 上午5 06 22" src="https://user-images.githubusercontent.com/38776510/114779455-bdd74380-9da8-11eb-81c2-8ea07eaa60c6.png">

**Comment by blueworrybear** [comment]
I notice that users actually can add new tag by themselves.
So would you like to prevent user from adding new tags?

If so, it seems to me that we should remove the original input field and replace it with a new one.

**Comment by AB-Y** [comment]
I tried to use different kinds of identity: member, wiki-editor, and administrator
it looks like only administrators COULD add new tags if they want. 
Hence I think we still need to remove 「開始錄製」 whenever it appears. (Admin can add tag from dashboard)

Only if we want our beta users can add tags on their own in the first run...
I recommend we may remove this 'add tags' function in order to make things simple :)
 @kun-yu-tsai how about this?

**Comment by AB-Y** [comment]
目前暫時解法：先改「開始錄製」的翻譯，改為「最多輸入五個相近關鍵字標籤」

**Comment by blueworrybear** [comment]
@AB-Y 

It seems to me that changing the translation to "最多輸入五個相近關鍵字標籤" is not a good idea.
It's because the sentence is more like a hint for the input field itself, not for the popup window.

The ideal UI should look like below:

https://user-images.githubusercontent.com/1456219/115321452-6d038880-a1b6-11eb-8886-37c8362869e6.mp4

Although the UI is built with [Vuetify](https://vuetifyjs.com/en/components/autocompletes/#slots), we should be able to find some alternatives in React. I am going to change the translation to "搜尋籤標..." in short term and back to this issue after finishing most of the **"must to have"** issues.

BTW, you could access the live demo in [Codepen](https://codepen.io/blueworrybear/pen/dyNgbwE).

**Comment by kun-yu-tsai** [comment]
That UI in Vuetify looks really slick. Thanks for the investigation, Benno. Let's apply 搜尋籤標... for the time being.
